(define (problem car_prob)
    (:domain car)
    (:init (not (engineBlown))
            (running)
            (= d 0)
            (= a 0)
            (= v 0))
     (:goal (and(= d 30) (= v 0) (not(engineBlown))))
     (:metric minimize(total-time))
)
